'use strict';

const { summarize } = require('../index');

const SEV_ICON = { error: 'x', warn: '!', info: 'i' };

function renderMarkdown(findings, options = {}) {
  const s = summarize(findings);
  const out = [];
  out.push('### ci-doctor report');
  out.push('');
  if (findings.length === 0) {
    out.push('No findings. Workflows look clean.');
    return out.join('\n');
  }
  out.push(`**${s.total} finding(s)** - error ${s.error}, warn ${s.warn}, info ${s.info}`);
  out.push('');
  out.push('| Sev | File | Line | Rule | Issue |');
  out.push('| - | - | - | - | - |');
  for (const f of findings) {
    const msg = String(f.message).replace(/\|/g, '\\|').replace(/\n/g, ' ');
    out.push(`| ${SEV_ICON[f.severity] || f.severity} | \`${f.filename}\` | ${f.line} | \`${f.ruleId}\` | ${msg} |`);
  }
  if (options.includeSuggestions !== false) {
    const withSug = findings.filter((f) => f.suggestion);
    if (withSug.length) {
      out.push('');
      out.push('<details><summary>Suggestions</summary>');
      out.push('');
      for (const f of withSug) {
        out.push(`**${f.ruleId}** at \`${f.filename}:${f.line}\``);
        out.push('');
        out.push('```yaml');
        out.push(String(f.suggestion));
        out.push('```');
        out.push('');
      }
      out.push('</details>');
    }
  }
  out.push('');
  out.push('_generated by [ci-doctor](https://github.com/depmedicdev-byte/ci-doctor)_');
  return out.join('\n');
}

module.exports = { renderMarkdown };
